#!/bin/sh
# Maintain a tag list for files by creating tags.txt and 
# keeping track of tags in it.
# Author : Emad Pourhassani emad@emadp.xyz

[ -f tags.txt ] || touch tags.txt 

addtag()
{
        filepath=$(readlink -f "$2") # get filepath
        if grep -Fwq "$filepath" tags.txt; # check if file already has any tags
        then
                # Check if file already has the tag.
                if ( grep "$filepath" tags.txt | sed "s/.*://" | grep -Fwq "$1" ) 
                then
                        printf "FILE ALREADY HAS THE %s TAG\n" "$1"
                else
                        # If file is missing the tag, add it.
                        sed -i "/$2/ s/$/ $1/" tags.txt
                fi

        else    
                # if file is not already in tags.txt, tag it and add it.
                 echo "$filepath: $1" >> tags.txt
        fi
}

case $1 in
        a|addtag) addtag "$2" "$3";;
        l|list) cat tags.txt ;;
        h|help) printf "usage: givetags [option] [tag] [filename] \n" 
                printf "options: \n" 
                printf "\t a, addtag: adds given tag to file e.g: givetag a Metal song.mp3 \n" 
                printf "\t l, list: lists the tags in tags.txt e.g: givetag list \n" 
                printf "\t h, help: give this help list \n";; 
        *)     ;;
               
esac
exit $?
